version: "3.7"

services:
  flask:
    build: .
    container_name: pyApi-matheus
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - /mnt/c/Users/atail/Documents/GitHub/TestWebRota/api-flask-bd:/usr/src/app
    networks:
      - minha-rede

  db:
    image: mysql:5.7
    container_name: mysql-matheus
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "Users"
    ports:
      - "3306:3306"
    volumes:
      - /mnt/c/Users/atail/Documents/GitHub/TestWebRota/api-flask-bd/bd:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin-matheus
    environment:
      PMA_HOST: mysql-matheus
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/Users/atail/Documents/GitHub/TestWebRota/api-flask-bd/bd:/etc/phpmyadmin/config.user.inc.php
    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge